server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/contact?useSSL=false&serverTimezone=UTC
    username: root
    password: viveksaini9758
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
#           /login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:} 
#           /login/oauth2/code/github
            scope:
              - user:email
              - read:user 

security:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyForNetflixClonedefaultSecretKeyForNetflixCloneVivekSainiBobySainiAuthe}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookies-name: ${JWT_REFRESH_TOKEN_COOKIE_NAME:refreshToken}
    cookies-secure: ${JWT_COOKIES_SECURE:true}
    cookies-http-only: ${JWT_COOKIES_HTTP_ONLY:true}
    cookies-same-site: ${JWT_COOKIES_SAME_SITE:lax}
    cookies-domain: ${JWT_COOKIES_DOMAIN:localhost}
